##############################################################################
#                     _______  _______ _________ ______   _        _______   #
#  |\     /||\     /|(  ____ )(  ____ )\__   __/(  __  \ ( \      (  ____ \  #
#  | )   ( |( \   / )| (    )|| (    )|   ) (   | (  \  )| (      | (    \/  #
#  | (___) | \ (_) / | (____)|| (____)|   | |   | |   ) || |      | (__      #
#  |  ___  |  \   /  |  _____)|     __)   | |   | |   | || |      |  __)     #
#  | (   ) |   ) (   | (      | (\ (      | |   | |   ) || |      | (        #
#  | )   ( |   | |   | )      | ) \ \_____) (___| (__/  )| (____/\| (____/\  #
#  |/     \|   \_/   |/       |/   \__/\_______/(______/ (_______/(_______/  #
#                                                                            #
##########───(https://wiki.hyprland.org/Hypr-Ecosystem/hypridle/)───##########
#
#   REPLACED BY NOCTALIA-SHELL
#
#──────────────────────────────────────────────────────────────(EVERYTHING)───
general {
    lock_cmd            = pidof hyprlock || hyprlock --quiet --immediate-render
    before_sleep_cmd    = playerctl --all-players pause
}

#───────────────────────────────────────────────────────────────(LISTENERS)───
listener {      # 10 MINUTES
    timeout     = 600
    on-timeout  = ${lock_cmd}
}
listener {      # 15 MINUTES
    timeout     = 900
    on-timeout  = ${lock_cmd} && ${before_sleep_cmd} && systemctl suspend       #-then-hibernate
    on-resume   = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
}
listener {      #   IMMEDIATE
    timeout     = 0
    on-lid-close = ${lock_cmd} && ${before_sleep_cmd} && systemctl suspend
    on-resume   = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
}
