#!/bin/bash
###########
# NICHE WOFI-CLI
################
#
# FORGET OPENING/CLOSING DETACHED TERMINALS
main() {
    local MENU=("────EXIT────")
    local SELECTED=$(printf "%s\n" "${MENU[@]}" | wofi --dmenu --prompt "$~>" | tr -d '\n')
    
    if [ -n "$SELECTED" ] && [ "$SELECTED" != "────EXIT────" ]; then
        eval "$SELECTED" &>/dev/null &disown
    else
        return 0
    fi
}

# START
main
