#!/bin/bash
###########
# WOFI POWERMENU
################
#
# PROCESS USER INPUT AND POWERMENU METHODS
powermenu() {
    local CMD=$(echo "$@" | sed -E 's/^--?//')

    case "$CMD" in
        r|[Rr]eload|RELOAD)
            if [ $XDG_SESSION_DESKTOP =~ ^sway* ]; then
                swaymsg reload
            elif [ $XDG_SESSION_DESKTOP == "Hyprland" ]; then
                hyprctl reload
            else
                systemctl --user reload
                systemctl --user daemon-reload
                systemctl --user daemon-reexec
            fi
        ;;
        l|[Ll]ock|LOCK)
            loginctl lock-session
        ;;
        s|[Ss]uspend|SUSPEND)
            loginctl lock-session
            systemctl suspend
        ;;
        L|[Ll]ogout|LOGOUT)
            #loginctl kill-user $(whoami)
            systemctl soft-reboot
        ;;
        R|[Rr]eboot|REBOOT)
            systemctl reboot
        ;;
        B|[Bb]ios|BIOS)
            systemctl reboot --firmware-setup
        ;;
        S|[Ss]hutdown|SHUTDOWN)
            systemctl -i poweroff
        ;;
        [hH]*)
            echo -e "\n\tPOWERMENU_OPTIONS"
            echo -e "─────────────────────────────────────────"
            echo -e "HELP:\t\tH|h\t    Help|help"
            echo -e "OPTIONAL:\t-\t\t--"
            echo -e "─────────────────────────────────────────"
            echo -e "RELOAD:\t\tr\t  Reload|reload"
            echo -e "LOCK:\t\tl\t    Lock|lock"
            echo -e "SUSPEND:\ts\t Suspend|suspend"
            echo -e "LOGOUT:\t\tL\t  Logout|logout"
            echo -e "REBOOT:\t\tR\t  Reboot|reboot"
            echo -e "BIOS:\t\tB\t    Bios|bios"
            echo -e "SHUTDOWN:\tS\tShutdown|shutdown\n"
        ;;
        ""|*)
            exit 0
        ;;
    esac
}

# DISPLAY POWERMEU & HANDLE USER INPUT
main() {
    local INPUT="${1#--}"
    local MENU=("────EXIT────" "RELOAD" "LOCK" "SUSPEND" "LOGOUT" "REBOOT" "BIOS" "SHUTDOWN")

    if [ -n "$INPUT" ]; then
        powermenu "$INPUT"
    else
        local SELECTED=$(printf "%s\n" "${MENU[@]}" | wofi --dmenu --prompt "POWERMENU")
        powermenu "$SELECTED"
    fi
}

# START
main "$@"
