#!/bin/bash
###########
# WOFI WRAPPER
##############
#
# CHECK FOR REQUIRED DEPENDENCIES
dependencies() {
    local PACKAGES=("wofi"
                    "wofi-calc"
                    "wofi-emoji"
                    "$HOME/.config/wofi/SCRIPTS/POWERMENU"
                    "$HOME/.config/wofi/SCRIPTS/COMMAND"
                    "$HOME/.config/APPLICATIONS")

    for CMD in "$PACKAGES"; do
        if ! command -v "$CMD" &>/dev/null; then
            notify-send -u critical -a "WOFI" "$0" "$CMD" "MISSING:" ||
            echo "WOFI: [$CMD] MISSING OR NOT IN PATH" >&2
        fi
    done
}

# PROCESS USER INPUT AND MENU METHODS
wofimenu() {
    case "$1" in
        "WOFI")
            wofi
        ;;
        "CALCULATOR")
            wofi-calc
        ;;
        "EMOJI")
            wofi-emoji
        ;;
        "POWERMENU")
            $HOME/.config/wofi/SCRIPTS/POWERMENU
        ;;
        "COMMAND")
            $HOME/.config/wofi/SCRIPTS/COMMAND
        ;;
        "APPLICATIONS")
            $HOME/.config/APPLICATIONS
        ;;
        ""|*)
            exit 0
        ;;
    esac
}

# DISPLAY APPLICATIONS+SCRIPTS & HANDLE USER INPUT
main() {
    local MENU=("────EXIT────" "WOFI" "CALCULATOR" "EMOJI" "POWERMENU" "COMMAND" "APPLICATIONS")
    local SELECTED=$(printf "%s\n" "${MENU[@]}" | wofi --dmenu --prompt "MENU")
    
    dependencies
    wofimenu "$SELECTED"
}

# START
main
