# wallust v3.5
#
#====================( BACKEND )====================#
# full - resized - wal - thumb -  fastresize - kmeans
backend = "kmeans"

#====================( COLORS )====================#
# lab - labmixed - lch - lchmixed - salience
color_space = "salience"

# dark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
# saliencedark - saliencedarkbalanced - saliencedarkdistributed - saliencedarklow (each has the 16 variations)
# salienceligh - saliencelightbalanced - saliencelightdistributed - saliencelightlow (each has the 16 variations)
palette = "saliencedarkdistributed"

# disabled by default
#check_contrast = true

# 1% and 100% (OPTIONAL, disabled by default)
#saturation = 35

# default 100 (no other use whatsoever)
#alpha = 100

#====================( THRESHOLD )====================#
# 1     Not Perceptible by human eyes.
# 1-2   Perceptible through close observation.
# 2-10  Perceptible at a glance.
# 11-49 Colors are more similar than opposite.
# 100   Colors are exact opposite.
threshold = 8

#====================( HOOKS )====================#
no_hooks = true

[hooks]
wallpaper = '''awww img "$(find $HOME/Pictures/Wallpapers -type f -exec file --mime-type {} + | grep 'image/' | cut -d: -f1 | shuf -n 1)"'''
#----(WAYPAPER)----#
#post_command = sh -c 'case "$(file -bi "$wallpaper")" in image/*) wallust run "$wallpaper" ;; video/*) t=$(mktemp --suffix=.png) && ffmpeg -v 0 -y -i "$wallpaper" -vf thumbnail -vframes 1 "$t" >/dev/null 2>&1 && wallust run "$t" && rm -f "$t" ;; esac'

#====================( TEMPLATES )====================#
[templates]
#----(COLORS)----#
colors.template = 'colors.txt'
colors.target = 'wallust.txt'
#----(GHOSTTY)----#
#ghostty.template = 'ghostty.conf'
#ghostty.target = '~/.config/ghostty/wallust.conf'
#----(NOCTALIA)----#
#noctalia.template = '../../noctalia/colors.conf'
#noctalia.target = '~/.config/noctalia/wallust.conf'
#----(NIRI)----#
#niri.template = '../../niri/colors.kdl'
#niri.target = '~/.config/niri/wallust.kdl'
#----(HYPRLAND)----#
#hyprland.template = '~/.config/hypr/colors.conf'
#hyprland.target = '~/.config/hypr/wallust.conf'
