# wallust v3.5
#
#====================( BACKEND )====================#
# full - resized - wal - thumb -  fastresize - kmeans
backend = "kmeans"

#====================( COLORS )====================#
# lab - labmixed - lch - lchmixed - salience
color_space = "salience"

# dark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
# saliencedark - saliencedarkbalanced - saliencedarkdistributed - saliencedarklow (each has the 16 variations)
# salienceligh - saliencelightbalanced - saliencelightdistributed - saliencelightlow (each has the 16 variations)
palette = "saliencedarkdistributed"

# disabled by default
#check_contrast = true

# 1% and 100% (OPTIONAL, disabled by default)
#saturation = 35

# default 100 (no other use whatsoever)
#alpha = 100

#====================( THRESHOLD )====================#
# 1     Not Perceptible by human eyes.
# 1-2   Perceptible through close observation.
# 2-10  Perceptible at a glance.
# 11-49 Colors are more similar than opposite.
# 100   Colors are exact opposite.
threshold = 8

#====================( HOOKS )====================#
# Disables hooks completly
no_hooks = true

[hooks]
wallpaper = '''awww img "$(find $HOME/Pictures/Wallpapers -type f -exec file --mime-type {} + | grep 'image/' | cut -d: -f1 | shuf -n 1)"'''

#====================( TEMPLATES )====================#
[templates]
#====================#
#----( Python )----#
python.template = '../sources/colors.py'
python.target = '~/.config/wallust/templates/wallust.py'
#----( JavaScript )----#
js.template = '../sources/colors.js'
js.target = '~/.config/wallust/templates/wallust.js'
#----( JSON )----#
json.template = '../sources/colors.json'
json.target = '~/.config/wallust/templates/wallust.json'
#----( CSS )----#
css.template = '../sources/colors.css'
css.target = '~/.config/wallust/templates/wallust.css'
#----( RASI )----#
rasi.template = '../sources/colors.rasi'
rasi.target = '~/.config/wallust/templates/wallust.rasi'
#----( Rust )----#
rust.template = '../sources/colors.rs'
rust.target = '~/.config/wallust/templates/wallust.rs'
#----( Lua )----#
lua.template = '../sources/colors.lua'
lua.target = '~/.config/wallust/templates/wallust.lua'
#----( YAML )----#
yaml.template = '../sources/colors.yaml'
yaml.target = '~/.config/wallust/templates/wallust.yaml'
#----( TOML )----#
toml_cfg.template = '../sources/colors.toml'
toml_cfg.target = '~/.config/wallust/templates/wallust.toml'
#----( C Header )----#
c_header.template = '../sources/colors.h'
c_header.target = '~/.config/wallust/templates/wallust.h'
#----( Emacs Lisp )----#
emacs.template = '../sources/colors.el'
emacs.target = '~/.config/wallust/templates/wallust.el'
#----( xresources )----#
xresources.template = '../sources/Xresources'
xresources.target = '~/.config/wallust/templates/Xresources'
#====================#
#----( GHOSTTY )----#
ghostty.template = '../../ghostty/colors.conf'
ghostty.target = '~/.config/ghostty/wallust.conf'
#----( NOCTALIA-SHELL )----#
noctalia.template = '../../noctalia/colors.conf'
noctalia.target = '~/.config/noctalia/wallust.conf'
#----( ROFI )----#
#rofi.template = '../../rofi/colors.rasi'
#rofi.target = '~/.config/rofi/wallust.rasi'
#----( NIRI )----#
niri.template = '../../niri/colors.conf'
niri.target = '~/.config/niri/wallust.conf'
#----( HYPRLAND )----#
hyprland.template = '../../hypr/colors.conf'
hyprland.target = '~/.config/hypr/wallust.conf'
