-- Generated by nwg-displays on 2026-06-14 at 18:05:15. Do not edit manually.

hl.monitor({
    output = "desc:BNQ ZOWIE XL LCD EBSCL02631SL0",
    mode = "1920x1080@239.76",
    position = "0x480",
    scale = 1.0,
    bitdepth = 10
})
hl.monitor({
    output = "desc:BNQ ZOWIE XL LCD 97L01432SL0",
    mode = "1920x1080@144.0",
    position = "1920x0",
    scale = 1.0,
    bitdepth = 10,
    transform = 1
})
hl.monitor({
    output = "desc:TUR LianLi TURZX 0xF589AA74",
    mode = "1920x480@60.0",
    position = "3000x720",
    scale = 1.0,
    bitdepth = 10,
    transform = 2
})
