$primary = rgb(ffffff)
$surface = rgb(000000)
$secondary = rgb(c6c6c6)
$error = rgb(ffb4ab)
$tertiary = rgb(e2e2e2)
$surface_lowest = rgb(000000)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
