#!/bin/bash
###########
# CUSTOM WAYBAR-CAVA MODULE
###########################
#
# OBTAIN VARIABLES FROM WAYBAR OR USE DEFAULT
config="${config}"
temp="/tmp/waybarcava"
icon=(${icons:-" " "▁" "▂" "▃" "▄" "▅" "▆" "▇" "█"})
bars="${bar:-8}"
tooltip="${tooltip}"

# DYNAMICALLY CONCATENATE CAVA.CONF TO TEMP.CONFIG SPECIFICATION
modify_config() {
    local general=("bars=$bars")
    local output=("method=raw" "raw_target=/dev/stdout" "data_format=ascii" "ascii_max_range=${#icon[@]}")

    # ADAPT+FORMAT DEFAULT CAVA.CONF TO TEMP OTHERWISE CREATE TEMP
    if [ -f "$config" ]; then
        sed -e "s/\s*=\s*/=/g;s/^[[:space:]]*//;s/[[:space:]]*$//;/#.*/d" "$config">"$temp"
        for line in "${general[@]}"; do
            grep -q "^${line%%=*}=" "$temp" && sed -i "s/^${line%%=*}=.*/$line/" "$temp" || sed -i "/^\[general\]/a$line" "$temp"
        done
        for line in "${output[@]}"; do
            grep -q "^${line%%=*}=" "$temp" && sed -i "s/^${line%%=*}=.*/$line/" "$temp" || sed -i "/^\[output\]/a$line" "$temp"
        done
    else
        echo -e "[general]\nbars=$bars\n[output]\nmethod=raw\nraw_target=/dev/stdout\ndata_format=ascii\nascii_max_range=${#icon[@]}">"$temp"
    fi
}

# FORMAT BARS TO WAYBAR
format_status() {
    local dict=""
    for (( i=0; i<${#icon[@]}; i++ )); do
        dict+="s/;//g;s/$i/${icon[i]}/g;"
    done
    cava -p "$temp" | sed "$dict"
}

# FORMAT TOOLTIP TO WAYBAR
format_tooltip() {
    if [ "$tooltip" = true ]; then
        text=$(playerctl metadata --format '{{artist}} - {{title}}')
        playerctl metadata --format '{"text": "'"$text"'", "tooltip": "{{playerName}} : {{artist}} - {{title}}"'
    fi
}

# CUSTOM WAYBAR CAVA MODULE HANDLING 
main() {
    modify_config
    format_status
    format_tooltip   # WIP
}

# START
main
