#!/bin/bash
#
################################################################################
#                                                                              #
#   ▄▀▀▀▀▄  ▄▀▀▀█▀▀▄  ▄▀▀█▄   ▄▀▀▄▀▀▀▄  ▄▀▀▀█▀▀▄  ▄▀▀▄ ▄▀▀▄  ▄▀▀▄▀▀▀▄  ▄▀▀▀▀▄  #
#  █ █   ▐ █    █  ▐ ▐ ▄▀ ▀▄ █   █   █ █    █  ▐ █   █    █ █   █   █ █ █   ▐  #
#     ▀▄   ▐   █       █▄▄▄█ ▐  █▀▀█▀  ▐   █     ▐  █    █  ▐  █▀▀▀▀     ▀▄    #
#  ▀▄   █     █       ▄▀   █  ▄▀    █     █        █    █      █      ▀▄   █   #
#   █▀▀▀    ▄▀       █   ▄▀  █     █    ▄▀          ▀▄▄▄▄▀   ▄▀        █▀▀▀    #
#   ▐      █         ▐   ▐   ▐     ▐   █                    █          ▐       #
#          ▐                           ▐                    ▐                  #
#                                                                              #
################################################################################
#
#   IF [ XDG_SESSION_DESKTOP = "TTY" ]; THEN ECHO "STILL_SAFE_TO_RUN_SCRIPT"; FI
#   SCRIPT WRAPPER (AUR): GNOME-TWEAKS>STARTUP_APPLICATIONS & XDG-AUTOSTART
#
#─────────────────────────────────────────────────────────────────(GSETTINGS)───
#gsettings set org.gnome.desktop.interface <THEME> <THEME>
gsettings set org.gnome.desktop.interface clock-format 24h

#───────────────────────────────────────────────────────────────(EXECUTABLES)───
main() {
    local INPUT="$@"
    local WAYLAND="--enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturer --ozone-platform-hint=auto"

    #─DESCENDING_LIST
    local APPLICATIONS=(
        "bash -c backup && bash -c exp_env"
        "dbus-update-activation-environment --systemd --all"
        "gnome-keyring-daemon --start --components=secrets"
        "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
        "xdg-autostart"                                # AUTOSTARTS APPLICATIONS
        "wlsunset -s 22:00 -S 10:00 -d 60"
        "mpd --systemd"
        #"wl-paste --type text --watch cliphist store"
        #"wl-paste --type image --watch cliphist store"
        #───(MINIMIZED_FLAGS)───#
        #"emacs --daemon"
        #"openrgb --startminimized"
        #"steam -silent $WAYLAND"
        #"vesktop --start-minimized $WAYLAND"
        #"telegram-desktop -startintray"
        #"youtube-music --use-tray-icon $WAYLAND"
        #"teams --startminimized $WAYLAND"
    )

    #─LAUNCH_OR_RELAUNCH_APPS
    for APP in "${APPLICATIONS[@]}"; do
        local NAME="${APP%% *}"

        case $INPUT in
            -[Hh]*|--[Hh]*)
			    echo -e "\n./$0 -[H/R/ ]\n"
			    echo -e "-[   H/help   ]: Help Menu"
			    echo -e "-[ R/relaunch ]: Relaunch Apps"
			    echo -e "-[   K/kill   ]: Kill All Apps"
			    echo -e "-[            ]: Auto-Launch Apps [DEFAULT]\n"
                return 0
		    ;;
            -[Rr]*|--[Rr]*)
                echo -e "RELAUNCHING:\t"$APP""
                pkill -9 "$NAME" &>/dev/null
                eval "$APP" &>/dev/null &disown
            ;;
	-[Kk]*|--[Kk]*)
		echo -e "KILLING:\t"$APP""
		pkill -9 "$NAME" &>/dev/null
	;;
            ""|*)
                if ! pgrep -f "$NAME" &>/dev/null; then
                    echo -e "LAUNCHING:\t"$APP""
                    eval "$APP" &>/dev/null &disown
                else
                    ps -C "$NAME" fh -Hw
                fi
            ;;
        esac
    done
}

#───START
main "$@"
