#!/bin/bash
#
################################################################################
#                                                                              #
#   ▄▀▀▀▀▄  ▄▀▀▀█▀▀▄  ▄▀▀█▄   ▄▀▀▄▀▀▀▄  ▄▀▀▀█▀▀▄  ▄▀▀▄ ▄▀▀▄  ▄▀▀▄▀▀▀▄  ▄▀▀▀▀▄  #
#  █ █   ▐ █    █  ▐ ▐ ▄▀ ▀▄ █   █   █ █    █  ▐ █   █    █ █   █   █ █ █   ▐  #
#     ▀▄   ▐   █       █▄▄▄█ ▐  █▀▀█▀  ▐   █     ▐  █    █  ▐  █▀▀▀▀     ▀▄    #
#  ▀▄   █     █       ▄▀   █  ▄▀    █     █        █    █      █      ▀▄   █   #
#   █▀▀▀    ▄▀       █   ▄▀  █     █    ▄▀          ▀▄▄▄▄▀   ▄▀        █▀▀▀    #
#   ▐      █         ▐   ▐   ▐     ▐   █                    █          ▐       #
#          ▐                           ▐                    ▐                  #
#                                                                              #
################################################################################
#
#───────────────────────────────────────────────────────────────────(EXPORTS)───
export WAYLAND="--enable-features=UseOzonePlatform --ozone-platform=wayland"
#export TRAY="-silent -startintray --start-in-tray --use-tray-icon --start-minimized --startminimized --minimized"
export ILENT="&>/dev/null &disown"

#─────────────────────────────────────────────────────────────────(GSETTINGS)───
#gsettings set org.gnome.desktop.interface theme <THEME>

#───────────────────────────────────────────────────────────────(EXECUTABLES)───
main() {
    #─DESCENDING_LIST
    applications=(
        "bash"
        "dbus-update-activation-environment --systemd --all"
        "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
        "gnome-keyring-daemon --start --components=secrets"
        #"dex-autostart -a $HOME/.config/autostart/*"
        "wlsunset -s 22:00 -S 10:00 -d 60"
        "nm-applet"
        "blueman-applet"
        "waypaper"
        #"emacs --daemon"
        #"eww daemon& eww open bar"
        "waybar"
        "dunst"
        "flameshot"
        "corectrl"
        "openrgb --startminimized"
        #"easyeffects"                                  # NO MINIMIZED LAUNCH
        #"obs"
        #"steam $WAYLAND -silent"
        #"lutris"                                       # NO MINIMIZED LAUNCH
        "vesktop $WAYLAND --start-minimized"
        "signal-desktop-beta $WAYLAND"
        "telegram-desktop -startintray"
        "youtube-music $WAYLAND --use-tray-icon"
        #"remmina"                                      # NO MINIMIZED LAUNCH
        #"virt-manager"                                 # NO MINIMIZED LAUNCH
        "betterbird"                                    # NO MINIMIZED LAUNCH
        #"teams $WAYLAND --startminimized"
        #"zoom $WAYLAND"                                # NO MINIMIZED LAUNCH
        "wl-paste --type text --watch cliphist store"   # CLIPBOARD TEXT DATA
        "wl-paste --type image --watch cliphist store"  # CLIPBOARD IMAGE DATA
    )

    #─LAUNCH_APPS_IF_NOT_LAUNCHED
    for app in "${applications[@]}"; do
        name="${app%% *}"

        if ! pgrep -f "$name" &>/dev/null; then
            echo "LAUNCHING: $app"
            eval $app $ILENT
        elif pgrep -f "$name" &>/dev/null; then
            pkill -9 "$name" &>/dev/null
            echo "RELAUNCHING: $app"
            eval $app $ILENT
        else
            echo "NO-PR0CCESS: $app" 
        fi
    done
}

#───START
main
