#!/bin/bash
###########
# WOFI POWERMENU
################
#
# PROCESS USER INPUT AND POWERMENU METHODS
powermenu() {
    case "$1" in
        "Reload")
            if [ $XDG_SESSION_DESKTOP =~ ^sway* ]; then
                swaymsg reload
            elif [ $XDG_SESSION_DESKTOP == "hyprland" ]; then
                hyprctl reload
            else
                systemctl --user reload
                systemctl --user daemon-reload
                systemctl --user daemon-reexec
            fi
        ;;
        "Lock")
            loginctl lock-session
        ;;
        "Suspend")
            loginctl lock-session
            systemctl suspend
        ;;
        "Logout")
            loginctl terminate-session "$XDG_SESSION_ID"
            loginctl kill-user $(whoami)
        ;;
        "Reboot")
            systemctl reboot
        ;;
        "Reboot>BIOS")
            systemctl reboot --firmware-setup
        ;;
        "Shutdown")
            systemctl poweroff
        ;;
    esac
}

# DISPLAY POWERMEU & HANDLE USER INPUT
main() {
    local menu=("Reload"
    			"Lock"
    			"Suspend"
    			"Logout"
    			"Reboot"
    			"Reboot>BIOS"
    			"Shutdown"
    			"<──EXIT──>")
    local selected=$(printf "%s\n" "${menu[@]}" | wofi --dmenu --prompt "<Power_Menu>" | tr -d '\n')
    powermenu "$selected"
}

# START
main
