#!/bin/bash
###########
# WOFI POWERMENU
################
#
# PROCESS USER INPUT AND POWERMENU METHODS
powermenu() {
    case "$1" in
        "RELOAD")
            if [ $XDG_SESSION_DESKTOP =~ ^sway* ]; then
                swaymsg reload
            elif [ $XDG_SESSION_DESKTOP == "Hyprland" ]; then
                hyprctl reload
            else
                systemctl --user reload
                systemctl --user daemon-reload
                systemctl --user daemon-reexec
            fi
        ;;
        "LOCK")
            loginctl lock-session
        ;;
        "SUSPEND")
            loginctl lock-session
            systemctl suspend
        ;;
        "LOGOUT")
            loginctl terminate-session "$XDG_SESSION_ID"
            loginctl kill-user $(whoami)
        ;;
        "REBOOT")
            systemctl reboot
        ;;
        "BIOS")
            systemctl reboot --firmware-setup
        ;;
        "SHUTDOWN")
            systemctl poweroff
        ;;
        "────EXIT────"|""|*)
            exit 0
        ;;
    esac
}

# DISPLAY POWERMEU & HANDLE USER INPUT
main() {
    local MENU=("RELOAD" "LOCK" "SUSPEND" "LOGOUT" "REBOOT" "BIOS" "SHUTDOWN" "────EXIT────")
    local SELECTED=$(printf "%s\n" "${MENU[@]}" | wofi --dmenu --prompt "POWERMENU" | tr -d '\n')
    powermenu "$SELECTED"
}

# START
main
